name: toybox CI

on:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ master ]
  pull_request:

jobs:
  MacOS:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v6
    - name: Setup
      run: brew install gnu-sed
    - name: Configure
      run: make macos_defconfig
    - name: Build
      run: make
    - name: Test
      run: VERBOSE=all make tests

  Ubuntu:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - name: Setup
      run: sudo apt-get install build-essential
    - name: Configure build and test
      run: VERBOSE=all CC=clang make defconfig tests
